### PR TITLE
Added Mixlr OEmbedProvider

### PR DESCRIPTION
**Pull request by bryanjos**
OEmbedProvider for mixlr.com

### CODE REVIEW

**Comment by starfishmod** [comment]
This look great! Have you got a mixlr url I can test it with?

**Comment by bryanjos** [comment]
http://mixlr.com/livemusicnola is the one I was using and the reason I added the OEmbedProvider. 

Here are some live ones right now.
http://mixlr.com/iarekylew00t
http://mixlr.com/wolfgang-roth

If you need more, here is the link to see all live electronica feeds:
http://mixlr.com/live/electronica/

**Comment by starfishmod** [comment]
Btw I have merged and tested but be aware that most of the links you provided come up with 
"Embeddable player is now only available to premium account holders. If you think this is a mistake, contact support@mixlr.com."

**Comment by bryanjos** [comment]
I just saw that the embedded player is a premium thing. I should have used more links in my testing.

**Pull request merged**
